// The GitHub star count of every software item's repository, for the stars
// button on its card.
//
// Run by .github/workflows/refresh-stars.yml once a month, and by hand:
//
//   node scripts/collect-stars.mjs          # rewrites config/stars.json
//
// A repository that cannot be read keeps its last count, so a rate limit or a
// rename never turns a card's button into 0 or drops it.

import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import { readItems } from './lib/items.mjs';

const OUT = 'config/stars.json';
const token = process.env.GITHUB_TOKEN || execFileSync('gh', ['auth', 'token'], { encoding: 'utf8' }).trim();
const before = fs.existsSync(OUT) ? JSON.parse(fs.readFileSync(OUT, 'utf8')).stars : {};

const repos = [...new Set(readItems().map((r) => r.item).filter((i) => i.type === 'software' && i.repo).map((i) => i.repo))].sort();
const stars = {};
for (const repo of repos) {
  const res = await fetch(`https://api.github.com/repos/${repo}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
  });
  if (res.ok) stars[repo] = (await res.json()).stargazers_count;
  else if (repo in before) { stars[repo] = before[repo]; console.warn(`  ! ${repo}: ${res.status}, kept ${before[repo]}`); }
  else console.warn(`  ! ${repo}: ${res.status}, no count`);
}

const doc = {
  $comment: 'Generated by scripts/collect-stars.mjs. Do not edit by hand.',
  stars,
};
fs.writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`  wrote ${OUT}: ${Object.keys(stars).length} repositories`);
